name: Test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    name: Test Ubuntu 20
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: wget http://mirrors.kernel.org/ubuntu/pool/universe/r/rpm/rpm_4.17.0+dfsg1-4build1_amd64.deb
      - name: install
        run: sudo dpkg -i rpm_4.17.0+dfsg1-4build1_amd64.deb && sudo apt-get install -f
