name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Ubuntu 20
    runs-on: ubuntu-20.04
    steps:
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: lts/-2
      - name: test
        run: node --version
