name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Ubuntu 20
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: cat /usr/lib/rpm/platform/armv7hl-linux/macros
      - name: test 2
        run: cat /usr/lib/rpm/platform/armv7l-linux/macros
