name: Test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    name: Test Ubuntu 20
    runs-on: ubuntu-20.04
    steps:
      - name: test
        run: /bin/rpmbuild --help
