name: Test

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  test:
    name: Test Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ls /bin/*-strip
